### ISSUE TITLE
skos:definition

### ISSUE THREAD

**Issue by s0301132** [gtfierro/brick-builder#5]
Hi @gtfierro, I want to add `skos:definition` to brick model using `brick-builder`, however when I do this there are some error occurred :
```
Exception: "https://www.***.hk/en/about_us/map_flm.html#"Testing_definition"@en" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```

Since definition is not a URI is it possible to add definition through `brick-builder`? Thanks

**Comment by gtfierro** [comment]
Make sure you are using the latest code from GitHub, but it is highly likely there's a bug in my code somewhere. I believe you will want the template part to look like

```
$1 skos:definition "$2"
```

which will ensure that `$2` is encoded as a literal. Can you give that a try?

**Comment by s0301132** [comment]
@gtfierro Using your example it can add definition to brick model, there are no bug about the program, just msiing the `""` in spo, Thanks!
